version: '3.9'
services:
  metabase:
    image: moritalous/metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    - ./metabase-data:/metabase-data
    ports:
      - 3333:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      JAVA_TIMEZONE: Asia/Tokyo
