# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: '3.7'

services:
  greengrass:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GREENGRASS_RELEASE_VERSION=2.5.1
    container_name: aws-iot-greengrass
    image: aws-iot-greengrass
    # environment:
    #   - PROVISION=true
    volumes:
      - ./greengrass/v2:/greengrass/v2
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./.aws:/root/.aws/:ro
