version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: '=JST-9'
      USERID: 1000
      GROUPID: 1000
    ports:
#      - "137:137/udp"
#      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./mnt:/mnt:z
    command: '-s "Mount;/mnt;yes;no;yes;all" -r -S -p'
    mem_limit: 256M
