version: '3.9'

services:
  telegraf:
    build: 
      context: .
      dockerfile: Dockerfile
    # image: telegraf
    security_opt:
      - seccomp=unconfined
    network_mode: host
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    volumes:
      - './telegraf.conf:/etc/telegraf/telegraf.conf:ro'
      - '/:/hostfs:ro'
